lando-plugin sets dist correctly, and also allows meta to be added

diff --git a/.github/workflows/pr-options-tests.yml b/.github/workflows/pr-options-tests.yml
--- a/.github/workflows/pr-options-tests.yml
+++ b/.github/workflows/pr-options-tests.yml
@@ -39,6 +39,9 @@ jobs:
             touch riker
             touch picard
           lando-plugin: false
+          meta:
+            captain=sisko
+            other-thing=kira
           root: ${{ github.workspace }}
           sync: false
           sync-email: william.t.riker@starfleet.mil
@@ -53,6 +56,28 @@ jobs:
             echo "::notice title=TEST PASSED::Version set in package.json correctly"
           else
             echo "::error title=TEST FAILED!::Version not set in package.json correctly"
+            exit 1
+          fi
+        shell: bash
+
+      - name: "TEST: should set the meta in the package.json"
+        if: always()
+        run: |
+          if cat "${{ github.workspace }}/package.json" | grep captain | grep sisko; then
+            echo "::notice title=TEST PASSED::Meta set in package.json correctly"
+          else
+            echo "::error title=TEST FAILED!::Meta not set in package.json correctly"
+            exit 1
+          fi
+        shell: bash
+
+      - name: "TEST: should set the meta in the package.json"
+        if: always()
+        run: |
+          if cat "${{ github.workspace }}/package.json" | grep other-thing | grep kira; then
+            echo "::notice title=TEST PASSED::Meta set in package.json correctly"
+          else
+            echo "::error title=TEST FAILED!::Meta not set in package.json correctly"
             exit 1
           fi
         shell: bash
